### ISSUE TITLE
JuiceNet API reference

### ISSUE THREAD

**Issue by edasque** [ketsugi/node-juicenet#3]
I'd love to contribute to this. Is there a reference to the JuiceNet API somewhere?

**Comment by jdmedeiros** [comment]
Me too. [This](https://filedn.com/l8OQOK51ql1J391d2ApmLb0/arq/juicenet/JuiceNet%20API_client_12_11_2017.docx) is the only thing I could find.

**Comment by edasque** [comment]
Thank you.
